#!/bin/bash

TEMP=$(getopt -o f:hv -l file:,help,verbose -- "$@")
eval set -- $TEMP

htpasswd="htpasswd"
file=".htpasswd"
: ${DIALOG=dialog}

: ${DIALOG_OK=0}
: ${DIALOG_CANCEL=1}
: ${DIALOG_HELP=2}
: ${DIALOG_EXTRA=3}
: ${DIALOG_ITEM_HELP=4}
: ${DIALOG_ESC=255}


while true
do
    case "$1" in
        -f|--file)
            file=$2
            shift 2
            ;;
        -h|--help)
            say_help
            shift
            exit 0
            ;;
        -v|--verbose)
            verbose=1
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Option '$1' not recognized"
            exit 1
            ;;
    esac
done

logins=""
if [ -f $file ]
then
    echo "reading file"
    logins=$(cat $file | cut -d: -f 1)

    checklist=""
    for login in logins
    do
        checklist+=" $login $login"
    done
fi

appTitle="htpasswd manager"
if [ $logins ]
then
    $DIALOG --title "$appTitle" \
        --extra-button \
        --extra-label "Delete" \
        --ok-label "Add" \
        --visit-items \
        --menu "Foo" 20 61 5 \
        $checklist 2> response
    r=$?
else
    $DIALOG --title "$appTitle" \
    --form "You have currently no login in that file" 20 61 15 \
    "login" 1 1 "" 1 10 20 0 \
    "password" 2 1 "" 2 10 20 0

fi

echo "r: $r - $(cat response)"
