#!/bin/bash

TEMP=$(getopt -o f:hvmBC:sp -l file:,help,verbose -- "$@")
eval set -- $TEMP

htpasswd="htpasswd"
file=".htpasswd"

## htpasswd options
md5=0
bcrypt=0
cost=""
sha=0
plain=0
: ${DIALOG=dialog}

: ${DIALOG_OK=0}
: ${DIALOG_CANCEL=1}
: ${DIALOG_HELP=2}
: ${DIALOG_EXTRA=3}
: ${DIALOG_ITEM_HELP=4}
: ${DIALOG_ESC=255}


htpasswdOptions=""
while true
do
    case "$1" in
        -f|--file)
            file=$2
            shift 2
            ;;
        -h|--help)
            say_help
            shift
            exit 0
            ;;
        -v|--verbose)
            verbose=1
            shift
            ;;

        ## options for htpasswd
        -m|-B|-s|-p)
            htpasswdOptions+="$1 "
            shift
            ;;
        -C)
            htpasswdOptions+="$1 $2"
            shift 2
            ;;

        ## end options for htpasswd

        --)
            shift
            break
            ;;
        *)
            echo "Option '$1' not recognized"
            exit 1
            ;;
    esac
done


function add_login() {
    login=""
    password=""
    exec 3>&1
    v=$($DIALOG --title "$appTitle" \
    --form "You have currently no login in that file" 20 61 15 \
    "login" 1 1 "" 1 10 20 0 \
    "password" 2 1 "" 2 10 20 0 2>&1 1>&3
    )
    r=$?
    exec 3>&-

    if [ $r -eq $DIALOG_CANCEL -o $r -eq $DIALOG_ESC ]
    then
        return 1
    fi

    login=$(echo $v | cut -d' ' -f 1)
    password=$(echo $v | cut -d' ' -f 2)

    options=""
    if [ ! -f $file ]
    then
        options="-c"
    fi
    htpasswd $htpasswdOptions -b $options $file $login $password
    ret=$?
    if [ $ret -ne 0 ]
    then
        return 1
    fi

    return 0
}

function delete_login() {
    loginToDelete=$1

    htpasswd $htpasswdOptions -D $file $loginToDelete
    ret=$?
    if [ $ret -ne 0 ]
    then
        return 4
    fi

    return 0
}

function list_login() {
    checklist=$@
    $DIALOG --title "$appTitle" \
        --extra-button \
        --extra-label "Delete" \
        --ok-label "Add" \
        --cancel-label "Exit" \
        --menu "Foo" 20 61 5 \
        $checklist 2> response
    r=$?
        #--visit-items \

    if [ $r -eq 1 ]
    then
        return 1
    fi

    if [ $r -eq 0 ]
    then
        add_login
    fi

    if [ $r -eq 3 ]
    then
        loginToDelete=$(cat response)
        delete_login $loginToDelete
        ret=$?
        if [ $ret -ne 0 ]
        then
            echo "message box error"
        fi

        return $DIALOG_OK
    fi
}

appTitle="htpasswd manager"


returnCode=0
while [ $returnCode -ne 1 -a $returnCode -ne 250 ]
do
    logins=""
    if [ -f $file ]
    then
        logins=$(cat $file | cut -d: -f 1)

        checklist=""
        for login in $logins
        do
            checklist+=" $login $login"
        done
    fi

    if [ ! -z "$logins" ]
    then
        list_login $checklist
        returnCode=$?
    else
        add_login
        returnCode=$?
    fi
done


exit 0
